# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/agcarat/my-src/NettyCpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/agcarat/my-src/NettyCpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/agcarat/my-src/NettyCpp/CMakeFiles /home/agcarat/my-src/NettyCpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/agcarat/my-src/NettyCpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named client_sync

# Build rule for target.
client_sync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_sync
.PHONY : client_sync

# fast build rule for target.
client_sync/fast:
	$(MAKE) -f CMakeFiles/client_sync.dir/build.make CMakeFiles/client_sync.dir/build
.PHONY : client_sync/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named server_sync

# Build rule for target.
server_sync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server_sync
.PHONY : server_sync

# fast build rule for target.
server_sync/fast:
	$(MAKE) -f CMakeFiles/server_sync.dir/build.make CMakeFiles/server_sync.dir/build
.PHONY : server_sync/fast

client.o: client.cc.o
.PHONY : client.o

# target to build an object file
client.cc.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cc.o
.PHONY : client.cc.o

client.i: client.cc.i
.PHONY : client.i

# target to preprocess a source file
client.cc.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cc.i
.PHONY : client.cc.i

client.s: client.cc.s
.PHONY : client.s

# target to generate assembly for a file
client.cc.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cc.s
.PHONY : client.cc.s

client_sync.o: client_sync.cc.o
.PHONY : client_sync.o

# target to build an object file
client_sync.cc.o:
	$(MAKE) -f CMakeFiles/client_sync.dir/build.make CMakeFiles/client_sync.dir/client_sync.cc.o
.PHONY : client_sync.cc.o

client_sync.i: client_sync.cc.i
.PHONY : client_sync.i

# target to preprocess a source file
client_sync.cc.i:
	$(MAKE) -f CMakeFiles/client_sync.dir/build.make CMakeFiles/client_sync.dir/client_sync.cc.i
.PHONY : client_sync.cc.i

client_sync.s: client_sync.cc.s
.PHONY : client_sync.s

# target to generate assembly for a file
client_sync.cc.s:
	$(MAKE) -f CMakeFiles/client_sync.dir/build.make CMakeFiles/client_sync.dir/client_sync.cc.s
.PHONY : client_sync.cc.s

server.o: server.cc.o
.PHONY : server.o

# target to build an object file
server.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cc.o
.PHONY : server.cc.o

server.i: server.cc.i
.PHONY : server.i

# target to preprocess a source file
server.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cc.i
.PHONY : server.cc.i

server.s: server.cc.s
.PHONY : server.s

# target to generate assembly for a file
server.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cc.s
.PHONY : server.cc.s

server_sync.o: server_sync.cc.o
.PHONY : server_sync.o

# target to build an object file
server_sync.cc.o:
	$(MAKE) -f CMakeFiles/server_sync.dir/build.make CMakeFiles/server_sync.dir/server_sync.cc.o
.PHONY : server_sync.cc.o

server_sync.i: server_sync.cc.i
.PHONY : server_sync.i

# target to preprocess a source file
server_sync.cc.i:
	$(MAKE) -f CMakeFiles/server_sync.dir/build.make CMakeFiles/server_sync.dir/server_sync.cc.i
.PHONY : server_sync.cc.i

server_sync.s: server_sync.cc.s
.PHONY : server_sync.s

# target to generate assembly for a file
server_sync.cc.s:
	$(MAKE) -f CMakeFiles/server_sync.dir/build.make CMakeFiles/server_sync.dir/server_sync.cc.s
.PHONY : server_sync.cc.s

test.pb.o: test.pb.cc.o
.PHONY : test.pb.o

# target to build an object file
test.pb.cc.o:
	$(MAKE) -f CMakeFiles/client_sync.dir/build.make CMakeFiles/client_sync.dir/test.pb.cc.o
	$(MAKE) -f CMakeFiles/server_sync.dir/build.make CMakeFiles/server_sync.dir/test.pb.cc.o
.PHONY : test.pb.cc.o

test.pb.i: test.pb.cc.i
.PHONY : test.pb.i

# target to preprocess a source file
test.pb.cc.i:
	$(MAKE) -f CMakeFiles/client_sync.dir/build.make CMakeFiles/client_sync.dir/test.pb.cc.i
	$(MAKE) -f CMakeFiles/server_sync.dir/build.make CMakeFiles/server_sync.dir/test.pb.cc.i
.PHONY : test.pb.cc.i

test.pb.s: test.pb.cc.s
.PHONY : test.pb.s

# target to generate assembly for a file
test.pb.cc.s:
	$(MAKE) -f CMakeFiles/client_sync.dir/build.make CMakeFiles/client_sync.dir/test.pb.cc.s
	$(MAKE) -f CMakeFiles/server_sync.dir/build.make CMakeFiles/server_sync.dir/test.pb.cc.s
.PHONY : test.pb.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... client"
	@echo "... client_sync"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... server_sync"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... client_sync.o"
	@echo "... client_sync.i"
	@echo "... client_sync.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... server_sync.o"
	@echo "... server_sync.i"
	@echo "... server_sync.s"
	@echo "... test.pb.o"
	@echo "... test.pb.i"
	@echo "... test.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

